version: '3' 

services:
  docker-project-template:
    image: openkbs/docker-project-template
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-project-template
    env_file:
      - ./.env
    environment:
      - USER_ID=${USER_ID:-1000}
      - GROUP_ID=${GROUP_ID:-1000}
      - DISPLAY=$DISPLAY
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
    volumes:
      - /run/dbus:/host/run/dbus
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./workspace:/home/developer/workspace
      - ./data:/home/developer/data
